# Generated by Django 4.2.30 on 2026-06-22 09:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_task_proceed_flag_task_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='meetings_invited', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='meeting',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetings', to='core.project'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='room_name',
            field=models.CharField(blank=True, editable=False, max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='platform',
            field=models.CharField(choices=[('Jitsi', 'Jitsi Meet')], default='Jitsi', max_length=20),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('live', 'Live'), ('ended', 'Ended'), ('cancelled', 'Cancelled')], default='upcoming', max_length=10),
        ),
    ]
